# SPDX-License-Identifier: MIT
"""Every sample rate stated as current truth must come from the generated file.

`docs/reference/core-facts.md` is generated by measurement precisely so rates
are not recalled from memory. On 2026-08-26 they were recalled from memory
anyway: a spike table labeled 32040 as NES (it is SNES), and Game Boy as 32768
(mGBA runs it at 131072). The second is a rate no pinned core produces, so that
row measured nothing - and the genuinely hardest ratio in the matrix, 131072
into 48000 at 2.73:1, went untested as a result. It was caught by a person
noticing a neighboring number, which is not a mechanism.

So: any `NNNN Hz` in a file that claims to describe how things are NOW must be a
rate core-facts records, or half of one - a Nyquist figure is the only derived
value that keeps turning up.

Deliberately NOT checked:

  docs/decisions/   ADRs are immutable once accepted and several correctly
                    record rates that have since been superseded. Failing on
                    those would mean editing history to satisfy a checker.
  docs/discussion/  dated logs; same argument.
  libretro-cores-survey.md
                    surveys cores that were evaluated and NOT pinned, so its
                    rates are real measurements of software we do not ship.

That exclusion list is the honest boundary of this check: it catches a stale
rate in code or in a current claim, and cannot catch one in a historical record.
"""
import pathlib, re, subprocess, sys

ROOT  = pathlib.Path(__file__).resolve().parent.parent
FACTS = ROOT / "docs/reference/core-facts.md"
SKIP  = ("docs/decisions/", "docs/discussion/",
         "docs/reference/libretro-cores-survey.md")
LOOK  = ("*.c", "*.h", "*.md")

if not FACTS.exists():
    sys.exit("check-rates: no core-facts.md; run tools/corefacts.sh")

rates = set()
for line in FACTS.read_text().splitlines():
    cells = [c.strip() for c in line.split("|")]
    if len(cells) > 2 and cells[-2].isdigit():
        rates.add(int(cells[-2]))
if not rates:
    sys.exit("check-rates: core-facts.md has no rate column")

# Derived figures, admitted one at a time and named. An earlier version allowed
# every rate's half as "a Nyquist figure", which quietly whitelisted 32768 -
# half of GBA's 65536, and the precise wrong number this check exists to catch.
# A rule broad enough to be convenient was broad enough to be useless.
DERIVED = {
    16020: "Nyquist of SNES's 32040, cited in the resampler spike",
}
allowed = rates | set(DERIVED)

files = subprocess.run(["git", "ls-files", *LOOK], cwd=ROOT,
                       capture_output=True, text=True).stdout.split()
bad = []
for rel in files:
    if rel.startswith(SKIP) or rel == "tools/check-rates.py":
        continue
    for n, line in enumerate((ROOT / rel).read_text(errors="ignore").splitlines(), 1):
        # (?<![\d.]) keeps "50.0070 Hz" out of this: that is a frame rate, and
        # its fractional part looks exactly like a sample rate to a plain \b.
        for m in re.finditer(r"(?<![\d.])(\d{4,6}) ?Hz\b", line):
            v = int(m.group(1))
            if v not in allowed:
                bad.append((rel, n, v, line.strip()[:88]))

for rel, n, v, text in bad:
    print(f"FAIL  {rel}:{n}: {v} Hz is not a rate core-facts.md records")
    print(f"        {text}")
if bad:
    print(f"\n{len(bad)} stale or invented rate(s). core-facts.md has: "
          + ", ".join(str(r) for r in sorted(rates)))
    print("If a figure is genuinely derived, add it to DERIVED with the reason "
          "rather than widening the rule.")
    sys.exit(1)
print("ok: every stated sample rate comes from core-facts.md")
