# SPDX-License-Identifier: MIT
"""Generate env_names.h from libretro.h.

Emits a number -> name lookup for RETRO_ENVIRONMENT_* commands, plus a predicate
for which ones carry the EXPERIMENTAL bit. Generated rather than hand-written so
the table cannot drift from the header it describes: libretro adds commands, and
a stale table would silently mislabel them.

The table is keyed on the FULL command value, experimental bit included, not on
the low 16 bits. That matters because the bit is not decoration - two distinct
commands share a number and are told apart only by it:

    #define RETRO_ENVIRONMENT_SET_SERIALIZATION_QUIRKS 44
    #define RETRO_ENVIRONMENT_SET_HW_SHARED_CONTEXT   (44 | RETRO_ENVIRONMENT_EXPERIMENTAL)

A table keyed on the masked number can only hold one of those, so it silently
mislabels the other. An earlier version did exactly that, and which one it lost
depended on iteration order.

usage:  python3 tools/gen_env_names.py src/libretro.h > tools/env_names.h
"""
import re
import sys

PATTERN = re.compile(
    r"^#define\s+(RETRO_ENVIRONMENT_[A-Z0-9_]+)\s+"
    r"\(?\s*(\d+)\s*(\|\s*RETRO_ENVIRONMENT_EXPERIMENTAL)?\s*\)?",
    re.M,
)

# These are the bit flags themselves, not commands.
SKIP = {"RETRO_ENVIRONMENT_EXPERIMENTAL", "RETRO_ENVIRONMENT_PRIVATE"}


def main(header):
    with open(header, encoding="utf-8") as fh:
        src = fh.read()

    EXPERIMENTAL = 0x10000

    seen = {}
    collisions = 0
    for match in PATTERN.finditer(src):
        name, number, experimental = match.group(1), int(match.group(2)), bool(match.group(3))
        if name in SKIP:
            continue
        full = number | (EXPERIMENTAL if experimental else 0)
        if full in seen:
            continue
        if any(k & 0xFFFF == number for k in seen):
            collisions += 1
        seen[full] = name[len("RETRO_ENVIRONMENT_"):]

    out = sys.stdout.write
    out("/* Generated by tools/gen_env_names.py. Do not edit.\n")
    out(" * Keyed on the FULL command value, experimental bit included: two\n")
    out(" * commands can share a number and differ only by that bit. */\n")
    out("static const char *diatom_env_name(unsigned cmd) {\n  switch (cmd) {\n")
    for full in sorted(seen):
        out('    case %d: return "%s";\n' % (full, seen[full]))
    out('    default: return "UNKNOWN";\n  }\n}\n')

    print(
        "commands: %d (%d share a number with another, told apart by the "
        "experimental bit)" % (len(seen), collisions),
        file=sys.stderr,
    )


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: gen_env_names.py <path to libretro.h>")
    main(sys.argv[1])
